pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = '211218518678.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app'
    IMAGE_TAG = "ecommerce-${BUILD_NUMBER}"
  }

  stages {
    stage('Checkout Code') {
      steps {
        git url: 'https://github.com/Git-Srinivas5/ecommerce-devops-project.git', branch: 'main'
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          sh 'docker build -t $ECR_REPO:$IMAGE_TAG ./backend'
        }
      }
    }

    stage('Login to AWS ECR') {
      steps {
        script {
          sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO'
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        script {
          sh 'docker push $ECR_REPO:$IMAGE_TAG'
        }
      }
    }
  }

  post {
    success {
      echo "Docker image pushed: $ECR_REPO:$IMAGE_TAG"
    }
    failure {
      echo "Build failed. Check logs."
    }
  }
}
