pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = '211218518678'
        ECR_REPO_NAME = 'ecommerce-app'
        IMAGE_TAG = 'v1'
        IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Git-Srinivas5/ecommerce-devops-project.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('backend') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t $ECR_REPO_NAME .'
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Tag & Push to ECR') {
            steps {
                sh '''
                docker tag $ECR_REPO_NAME:latest $IMAGE_URI
                docker push $IMAGE_URI
                '''
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f ecommerce || true
                docker run -d -p 9090:8080 --name ecommerce $IMAGE_URI
                '''
            }
        }
    }
}
